investments/urls.py
from django.urls import path

from . import views

app_name = 'investments'
urlpatterns = [
    path('', views.InvestmentListView.as_view(), name='index'),
    path('<int:investment_id>/', views.detail_investment, name='detail'),
    path('myinvestments/', views.list_user_investments, name='myinvestments'),
    path('search/', views.search_investments, name='search'),
    path('create/', views.create_investment, name='create'),
    path('delete/<int:investment_id>/', views.delete_investment, name='delete'),
    path('update/<int:investment_id>/', views.update_investment, name='update'),
]

investorsclub/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('staticpages.urls')),
    path('investments/', include('investments.urls')),
    path('tips/', include('tips.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

tips/urls.py
from django.urls import path

from . import views

app_name = 'tips'
urlpatterns = [
    path('', views.list_tips, name='index'),
    path('mytips/', views.list_user_tips, name='mytips'),
    path('<int:tips_id>/', views.detail_tips, name='detail'),
    path('search/', views.search_tips, name='search'), 
    path('create/', views.create_tips, name='create'),
    path('update/<int:tips_id>/', views.update_tips, name='update'),
    path('delete/<int:tips_id>/', views.delete_tips, name='delete'),
    path('<int:tips_id>/review/', views.create_review, name='review'),
    path('category/', views.CategoryListView.as_view(), name='category'),
    path('category/create', views.CategoryCreateView.as_view(), name='create-category'),
]

templates/partials/navbar_logged.html
{% load static %}
<header>
    
    
    <nav class="navbar navbar-expand-lg d-flex navbar-dark" style="background-color: #2E1C2B;">
        <span class="nav-brand"> <img src="{% static 'logo.svg' %}" width="80px"> </span>

        <ul class="navbar-nav p-2">
            
            <li class="nav-item">
                <a class="btn nav-link" href="{% url 'tips:index' %}">Blog</a>
            </li>
            <li class="nav-item">
                <a class="btn nav-link" href="{% url 'investments:index' %}">Ações</a>
            </li>

            <li class="nav-item">
                <a class="btn nav-link" href="{% url 'tips:category' %}">Categorias</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto p-2">
            <li class="nav-item mr-3">
                <a class="nav-link btn" href="{% url 'tips:mytips' %}">Meus posts</a>
            </li>
            <li class="nav-item mr-3">
                <a class="nav-link btn" href="{% url 'investments:myinvestments' %}">Minhas ações</a>
            </li>
            <li class="nav-item mr-3">
                <a class="nav-link btn" href="{% url 'logout' %}">Sair</a>
            </li>
        </ul>
    </nav>

</header>

templates/partials/navbar_unlogged.html
{% load static %}
<header>
    

    <nav class="navbar navbar-expand-lg d-flex navbar-dark bg-dark">
        <a href="{% url 'index' %}" class="nav-brand"> <img src="{% static 'logo.svg' %}" width="80px"> </a>

        <ul class="nav navbar-nav p-2">
            <li class="nav-item active">
                <a class="btn nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="btn nav-link" href="{% url 'tips:index' %}">Blog</a>
            </li>
            <li class="nav-item">
                <a class="btn nav-link" href="{% url 'investments:index' %}">Ações</a>
            </li>
        </ul>
        <ul class="nav navbar-nav ml-auto p-2">
            <li class="nav-item mr-3">
                <a class="nav-link btn btn-light" style="color: rgb(53, 52, 52)" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link btn btn-outline-light" href="{% url 'signup' %}">Cadastrar-se</a>
            </li>
        </ul>
    </nav>

</header>