investorsclub/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('staticpages.urls')),
    path('investments/', include('investments.urls')),
    path('tips/', include('tips.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

tips/urls.py
from django.urls import path

from . import views

app_name = 'tips'
urlpatterns = [
    path('', views.list_tips, name='index'),
    path('mytips/', views.list_user_tips, name='mytips'),
    path('<int:tips_id>/', views.detail_tips, name='detail'),
    path('search/', views.search_tips, name='search'), 
    path('create/', views.create_tips, name='create'),
    path('update/<int:tips_id>/', views.update_tips, name='update'),
    path('delete/<int:tips_id>/', views.delete_tips, name='delete'),
    path('<int:tips_id>/review/', views.create_review, name='review'),
    path('category/', views.CategoryListView.as_view(), name='category'),
    path('category/create', views.CategoryCreateView.as_view(), name='create-category'),
]

tips/models.py
from django.db import models
from django.conf import settings


class Tips(models.Model):
    title = models.CharField(max_length=20)
    content = models.CharField(max_length=10000)
    thumbnail = models.URLField(max_length=200, null=True)
    publisher = models.CharField(max_length=200)
    date = models.DateTimeField()

    def __str__(self):
        return f'{self.title}'

class Review(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    tips = models.ForeignKey(Tips, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'


class Category(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    desc = models.CharField(max_length=255)
    tips = models.ManyToManyField(Tips)

    def __str__(self):
        return f'{self.name}'

tips/forms.py
from django.forms import ModelForm
from .models import Tips, Review
from django import forms


class TipsForm(ModelForm):
    content = forms.CharField( widget=forms.Textarea )
    class Meta:
        model = Tips
        fields = [
            'title', 
            'content',
            'thumbnail',
        ]
        labels = {
            'title': 'Título', 
            'content': 'Conteúdo',
            'thumbnail': 'URL da Thumbnail',
        }
class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = [
            'text',
        ]
        labels = {
            'text': 'Resenha',
        }

tips/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from .models import Tips, Review, Category
from datetime import datetime
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from .forms import TipsForm, ReviewForm
# Create your views here.
def list_tips(request):
    tips_list = Tips.objects.all()
    context = {'tips_list': tips_list}
    return render(request, 'tips/index.html', context)

@login_required
def list_user_tips(request):
    tips_list = Tips.objects.filter(publisher=request.user)
    context = {'tips_list': tips_list}
    return render(request, 'tips/mytips.html', context)

def detail_tips(request, tips_id):
    tips = get_object_or_404(Tips, pk=tips_id)
    context = {'tips': tips}
    return render(request, 'tips/detail.html', context)

def search_tips(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        tips_list = Tips.objects.filter(title__icontains=search_term)
        context = {"tips_list": tips_list}
    return render(request, 'tips/search.html', context)

@login_required
def create_tips(request):
    if request.method == 'POST':
        form = TipsForm(request.POST)
        if form.is_valid():
            title = request.POST['title']
            content = request.POST['content']
            thumbnail = request.POST['thumbnail']
            date = datetime.now()
            publisher = request.user
            tips = Tips(title = title,
                        content = content,
                        thumbnail = thumbnail,
                        date = date, 
                        publisher = publisher)
            tips.save()
            return HttpResponseRedirect(
                reverse('tips:detail', args=(tips.id, )))
    else:
        form = TipsForm()
    context = {'form': form}
    return render(request, 'tips/create.html', context)

@login_required
def update_tips(request, tips_id):
    tips = get_object_or_404(Tips, pk=tips_id)

    if request.method == "POST":
        form = TipsForm(request.POST)
        if form.is_valid():
            title = request.POST['title']
            content = request.POST['content']
            thumbnail = request.POST['thumbnail']
            date = request.POST['thumbnail']
            publisher = request.user
            tips = Tips(title = title,
                        content = content,
                        thumbnail = thumbnail,
                        date = date, 
                        publisher = publisher)
            return HttpResponseRedirect(
                reverse('tips:detail', args=(tips.id, )))
    else:
        form = TipsForm(
            initial={
                'title': tips.title,
                'content': tips.content,
                'thumbnail': tips.thumbnail
            }
        )
    context = {'tips': tips, 'form': form}
    return render(request, 'tips/update.html', context)

@login_required
def delete_tips(request, tips_id):
    tips = get_object_or_404(Tips, pk=tips_id)

    if request.method == "POST":
        tips.delete()
        return HttpResponseRedirect(reverse('tips:index'))

    context = {'tips': tips}
    return render(request, 'tips/delete.html', context)
@login_required
def create_review(request, tips_id):
    tips = get_object_or_404(Tips, pk=tips_id)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review_author = request.user
            review_text = form.cleaned_data['text']
            review = Review(author=review_author,
                            text=review_text,
                            tips=tips)
            review.save()
            return HttpResponseRedirect(
                reverse('tips:detail', args=(tips_id, )))
    else:
        form = ReviewForm()
    context = {'form': form, 'tips': tips}
    return render(request, 'tips/review.html', context)

class CategoryListView(generic.ListView):
    model = Category
    template_name = 'tips/category.html'


class CategoryCreateView(generic.CreateView):
    model = Category
    template_name = 'tips/create-category.html'
    fields = ['name', 'author', 'desc','tips']
    success_url = reverse_lazy('tips:category')

tips/templates/tips/category.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}
<h2>Categorias de posts</h2>

<section>
    {% for category in category_list %}
    <hr>
    <article>
        <header>
            <h3>{{category.name}}</h3>
        </header>
        <div class="lista-de-cards">
            {% for tips in category.tips.all %}
            <div class="card">
                <a href="{% url 'tips:detail' tips.id %}"><img src="{{ tips.thumbnail }}"
                        alt=""></a>
                <p>{{ tips.title}}</p>
            </div>
            {% endfor %}
        </div>
    </article>
    {% endfor %}

    <a href="{% url 'tips:create-category' %}"><button>Crie sua Categoria</button></a>
</section>

{% endblock content %}

tips/templates/tips/create-category.html
{% extends 'base.html' %}

{% block title %}
Criar categoria
{% endblock title %}

{% block content %}
<h2>Criar categoria</h2>

<form action="{% url 'tips:create-category' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

tips/templates/tips/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Post</h2>
<form method="POST" action="{% url 'tips:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

tips/templates/tips/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'tips:delete' tips.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar o post "{{tips.title}}"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

tips/templates/tips/detail.html
{% extends 'base.html' %}

{% block title %}
{{ tips.title }}
{% endblock title %}

{% block content %}
    <h1>{{tips.title}}</h1>
    <span>{{tips.date}}, por {{tips.publisher}}</span>
    <p><i class="fas fa-tag mr-2"></i>{{ tips.category_set.all|join:", " }}</p>
    <img src="{{tips.thumbnail}}" class="rounded mx-auto d-block" width="800px">
    <div>
    {{tips.content|safe}}
</div>
    <a href="{% url 'tips:update' tips.id %}" class="btn btn-primary btn-lg px-4 mr-3">Editar</a >
    <a href="{% url 'tips:delete' tips.id%}" class="btn btn-danger btn-lg px-4">Excluir</a>

    <hr>

<section>
    <header>
        <h3>Resenhas</h3>
    </header>
    <ul>
        {% if tips.review_set.all %}
            {% for review in tips.review_set.all %}
                <figure>
                    <blockquote>
                        "{{ review.text }}"
                    </blockquote>
                    <figcaption>—{{ review.author }}
                </figure>
            {% endfor %}
        {% else %}
            <p>Ainda não existe nenhuma resenha.</p>
        {% endif %}
    </ul>
    
    <a href="{% url 'tips:review' tips.pk %}"><button>Crie sua Resenha</button></a>

</section>
{% endblock content %}

tips/templates/tips/index.html
{% extends 'base.html' %}
{% load static %}

{% block extrastyles %}
    <link rel="stylesheet" type="text/css"
        href="{% static 'cards.css' %}" />
{% endblock %}

{% block content %}
<h2>Todos os posts</h2>
<a href="{% url 'tips:create' %}" class="btn btn-primary">Adicionar Novo Post</a>
<br>

{% if tips_list %}
<section class="lista-de-cards">
    {% for tips in tips_list %}
    <article class="postcard dark blue">
        <a class="postcard__img_link" href="{% url 'tips:detail' tips.id %}">
            <img class="postcard__img " src="{{tips.thumbnail}}" alt="Image Title" />
        </a>
        <div class="postcard__text">
            <h1 class="postcard__title blue"><a href="{% url 'tips:detail' tips.id %}">{{tips.title}}</a></h1>
            <div class="postcard__subtitle small">
                <time datetime="2020-05-25 12:00:00">
                    <i class="fas fa-calendar-alt mr-2"></i>{{tips.date|date}}
                </time>
                <span>
                    Por: {{tips.publisher}}
                </span>
            </div>
            <div class="postcard__bar"></div>
            <div class="postcard__preview-txt">{{tips.content| truncatewords:50}}...</div>
            <ul class="postcard__tagbox">
                <li class="tag__item"><i class="fas fa-tag mr-2"></i>{{ tips.category_set.all|join:", " }}</li>
            </ul>
        </div>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post.</p>
{% endif %}


{% endblock content %}

tips/templates/tips/mytips.html
{% extends 'base.html' %}
{% load static %}

{% block extrastyles %}
    <link rel="stylesheet" type="text/css"
        href="{% static 'cards.css' %}" />
{% endblock %}

{% block content %}
<h2>Todos os meus posts</h2>
<section>
    
</section>
{% if tips_list %}
<section class="lista-de-cards">
    {% for tips in tips_list %}
    <article class="postcard dark blue">
        <a class="postcard__img_link" href="{% url 'tips:detail' tips.id %}">
            <img class="postcard__img " src="{{tips.thumbnail}}" alt="Image Title" />
        </a>
        <div class="postcard__text">
            <h1 class="postcard__title blue"><a href="{% url 'tips:detail' tips.id %}">{{tips.title}}</a></h1>
            <div class="postcard__subtitle small">
                <time datetime="2020-05-25 12:00:00">
                    <i class="fas fa-calendar-alt mr-2"></i>{{tips.date|date}}
                </time>
                <span>
                    Por: {{tips.publisher}}
                </span>
            </div>
            <div class="postcard__bar"></div>
            <div class="postcard__preview-txt">{{tips.content| truncatewords:50}}...</div>
            <ul class="postcard__tagbox">
                <li class="tag__item"><i class="fas fa-tag mr-2"></i>{{ tips.category_set.all|join:", " }}</li>
            </ul>
        </div>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Você ainda não publicou nada.</p> <a href="{% url 'tips:create' %}">Adicionar Novo Post</a></p>
{% endif %}


{% endblock content %}

tips/templates/tips/review.html
{% extends 'base.html' %}

{% block content %}
<h2>Resenhar Post {{ tips.title }})</h2>

<form action="{% url 'tips:review' tips.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Resenha</button>
</form>

<p><a href="{% url 'tips:detail' tips.id %}">Voltar para a página do filme</a></p>
{% endblock content %}

tips/templates/tips/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar o Post "{{ tips.title }}"</h2>
<form method="POST" action="{% url 'tips:update' tips.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}