investments/urls.py
from django.urls import path

from . import views

app_name = 'investments'
urlpatterns = [
    path('', views.InvestmentListView.as_view(), name='index'),
    path('<int:investment_id>/', views.detail_investment, name='detail'),
    path('myinvestments/', views.list_user_investments, name='myinvestments'),
    path('search/', views.search_investments, name='search'),
    path('create/', views.create_investment, name='create'),
    path('delete/<int:investment_id>/', views.delete_investment, name='delete'),
    path('update/<int:investment_id>/', views.update_investment, name='update'),
]

investorsclub/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('staticpages.urls')),
    path('investments/', include('investments.urls')),
    path('tips/', include('tips.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

tips/urls.py
from django.urls import path

from . import views

app_name = 'tips'
urlpatterns = [
    path('', views.list_tips, name='index'),
    path('mytips/', views.list_user_tips, name='mytips'),
    path('<int:tips_id>/', views.detail_tips, name='detail'),
    path('search/', views.search_tips, name='search'), 
    path('create/', views.create_tips, name='create'),
    path('update/<int:tips_id>/', views.update_tips, name='update'),
    path('delete/<int:tips_id>/', views.delete_tips, name='delete'),
    path('<int:tips_id>/review/', views.create_review, name='review'),
    path('category/', views.CategoryListView.as_view(), name='category'),
    path('category/create', views.CategoryCreateView.as_view(), name='create-category'),
]

investments/models.py
from django.db import models

class Investment(models.Model):
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=20, default = "XXXX")
    thumbnail = models.URLField(max_length=200, null=True)
    publisher = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.name} ({self.code})'

investments/forms.py
from django.forms import ModelForm
from .models import Investment


class InvestmentForm(ModelForm):
    class Meta:
        model = Investment
        fields = [
            'name', 
            'code',
            'thumbnail',
        ]
        labels = {
            'name': 'Nome da ação (Yahoo Finance)', 
            'code': 'Código da ação',
            'thumbnail': 'URL da Thumbnail',
        }

investments/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .forms import InvestmentForm
from .models import Investment
from .data import *
from django.contrib.auth.decorators import login_required
# Create your views here.
class InvestmentListView(generic.ListView):
    model = Investment
    template_name = 'investments/index.html'

@login_required
def list_user_investments(request):
    investments_list = Investment.objects.filter(publisher=request.user)
    context = {'investments_list': investments_list}
    return render(request, 'investments/myinvestments.html', context)

@login_required
def create_investment(request):
    if request.method == 'POST':
        form = InvestmentForm(request.POST)
        if form.is_valid():
            name = request.POST['name']
            code = request.POST['code']
            thumbnail = request.POST['thumbnail']
            publisher = request.user
            investment = Investment(name = name,
                        code = code,
                        thumbnail = thumbnail,
                        publisher = publisher)
            investment.save()
            return HttpResponseRedirect(
                reverse('investments:detail', args=(investment.id, )))
    else:
        form = InvestmentForm()
    context = {'form': form}
    return render(request, 'investments/create.html', context)

def search_investments(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        investment_list = Investment.objects.filter(name__icontains=search_term)
        context = {"investment_list": investment_list}
    return render(request, 'investments/search.html', context)

def detail_investment(request, investment_id):
    investment = get_object_or_404(Investment, pk=investment_id)
    graph = dataframe_30(investment.code)
    x = graph[1]
    performance = pct_increase(investment.code)
    price = graph[0]
    context = {'price': price, 'x': x, 'performance': performance, 'investment': investment}
    return render(request, 'investments/detail.html', context)


@login_required
def update_investment(request, investment_id):
    investment = get_object_or_404(Investment, pk=investment_id)

    if request.method == "POST":
        form = InvestmentForm(request.POST)
        if form.is_valid():
            name = request.POST['name']
            code = request.POST['code']
            thumbnail = request.POST['thumbnail']
            publisher = request.user
            investment = Investment(name = name,
                        code = code,
                        thumbnail = thumbnail,
                        publisher = publisher)
            investment.save()
            return HttpResponseRedirect(
                reverse('investments:detail', args=(investment.id, )))
    else:
        form = InvestmentForm(
            initial ={
                'name': investment.name,
                'code': investment.code,
                'thumbnail': investment.thumbnail
            }
        )
    context = {'investment': investment, 'form': form}
    return render(request, 'investments/update.html', context)

@login_required
def delete_investment(request, investment_id):
    investment = get_object_or_404(Investment, pk=investment_id)

    if request.method == "POST":
        investment.delete()
        return HttpResponseRedirect(reverse('investments:index'))

    context = {'investment': investment}
    return render(request, 'investments/delete.html', context)

investments/templates/investments/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir nova ação</h2>
<form method="POST" action="{% url 'investments:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    
    <button type="submit">Criar</button>
</form>

{% endblock content %}

investments/templates/investments/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'investments:delete' investment.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar a ação "{{investment}}"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

investments/templates/investments/detail.html
{% extends 'base.html' %}

{% block title %}
{{ investment }}
{% endblock title %}

{% block content %}
    <h1>{{investment.code}}</h1>
    <span>PERFORMANCE - 30D: </span>
    {% if performance < 0 %}

    <i class="fa fa-arrow-down" aria-hidden="true" style="color:red"></i><span style="color: red; font-weight: bold;"> {{ performance }}%</span>
    {%else %}
    <i class="fa fa-arrow-up" aria-hidden="true" style="color:green"></i><span style="color: green; font-weight: bold;"> {{ performance }}%</span>
    {%endif%}

    <br/>
    <div id="myPlot" style="width:100%;"></div>
    

    {% block scripts %}
    
    <script>
        var xArray = {{x|safe}};
        var yArray = {{price}};
        
        // Define Data
        var data = [{
        x: xArray,
        y: yArray,
        type: "scatter",
        mode: "lines"  
        }];
        
        
        // Define Layout
        var layout = {
            title: 'Variação do preço',
            xaxis: {
                title: 'Dias',
                titlefont: {
                family: 'Arial, sans-serif',
                size: 18,
                color: 'grey'
                },
                showticklabels: true,
                tickangle: 45,
                tickfont: {
                family: 'Old Standard TT, serif',
                size: 14,
                color: 'black'
                },
                exponentformat: 'e',
                showexponent: 'all'
            },
            yaxis: {
                title: 'Preço',
                titlefont: {
                family: 'Arial, sans-serif',
                size: 18,
                color: 'grey'
                },
                showticklabels: true,
                tickangle: 45,
                tickfont: {
                family: 'Old Standard TT, serif',
                size: 14,
                color: 'black'
                },
                exponentformat: 'e',
                showexponent: 'all'
            }
            };
        // Display using Plotly
        Plotly.newPlot("myPlot", data, layout);
        </script>
    
    {% endblock scripts %}
    
    <a href="{% url 'investments:update' investment.id %}" class="btn btn-primary btn-lg px-4 mr-3">Editar</a >
    <a href="{% url 'investments:delete' investment.id%}" class="btn btn-danger btn-lg px-4">Excluir</a>
    
{% endblock content %}

investments/templates/investments/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos os investmentos registrados</h2>
<a href="{% url 'investments:create' %}" class="btn btn-primary">Adicionar Nova Ação</a>
<br>
{% if investments_list %}
<section class="lista-de-cards">
    {% for investment in investments_list %}
    <div class="card" style="width: 18rem;">
        <img src="{{investment.thumbnail}}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{investment}}</h5>
          <a href="{% url 'investments:detail' investment.id %}" class="btn btn-primary">Ver mais</a>
        </div>
      </div>
    {% endfor %}
</section>
{% else %}
<span>Não foi encontrado nenhuma ação.</span><a href="{% url 'investments:create' %}">Adicionar Nova Ação</a>

{% endif %}

{% endblock content %}

investments/templates/investments/myinvestments.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos os meus investimentos</h2>
<a href="{% url 'investments:create' %}" class="btn btn-primary">Adicionar Nova Ação</a>
<br>
{% if investments_list %}
<section class="lista-de-cards">
    {% for investment in investments_list %}
    <div class="card" style="width: 18rem;">
        <img src="{{investment.thumbnail}}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{investment}}</h5>
          <a href="#" class="btn btn-primary">Ver mais</a>
        </div>
      </div>
    {% endfor %}
</section>
{% else %}
<span>Não foi encontrado nenhuma ação.</span><a href="{% url 'investments:create' %}">Adicionar Nova Ação</a>
{% endif %}

{% endblock content %}

investments/templates/investments/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Editar ação</h2>
<form method="POST" action="{% url 'investments:update' investment.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}